using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beamable.Common;
using Beamable.Common.Api;
using Beamable.Common.Api.Inventory;
using Beamable.Microservices.SuiFederation.Features.Accounts;
using Beamable.Microservices.SuiFederation.Features.Accounts.Exceptions;
using Beamable.Microservices.SuiFederation.Features.Contracts;
using Beamable.Microservices.SuiFederation.Features.Contracts.Exceptions;
using Beamable.Microservices.SuiFederation.Features.Contracts.Functions.Models;
using Beamable.Microservices.SuiFederation.Features.EthRpc;
using Beamable.Microservices.SuiFederation.Features.Minting;
using Beamable.Microservices.SuiFederation.Features.Minting.Storage;
using Beamable.Microservices.SuiFederation.Features.Transactions;
using Beamable.Sui.Common;
using Beamable.Server;
using Beamable.Server.Api.RealmConfig;
using Nethereum.Web3;

namespace Beamable.Microservices.SuiFederation
{
    [Microservice("SuiFederation", CustomAutoGeneratedClientPath =
        "Packages/com.beamable.sui/Runtime/Client/Autogenerated/SuiFederationClient")]
    public class SuiFederation : Microservice, IFederatedInventory<SuiCloudIdentity>
    {
        private static bool _initialized;


        public Promise<FederatedAuthenticationResponse> Authenticate(string token, string challenge, string solution)
        {
            throw new NotImplementedException();
        }

        public Promise<FederatedInventoryProxyState> GetInventoryState(string id)
        {
            throw new NotImplementedException();
        }

        public Promise<FederatedInventoryProxyState> StartInventoryTransaction(string id, string transaction, Dictionary<string, long> currencies, List<FederatedItemCreateRequest> newItems, List<FederatedItemDeleteRequest> deleteItems,
            List<FederatedItemUpdateRequest> updateItems)
        {
            throw new NotImplementedException();
        }
    }
}