//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.SuiFederation.SuiFederation"/> </summary
    public sealed class SuiFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedLogin<Beamable.Sui.Common.SuiCloudIdentity>, Beamable.Common.ISupportsFederatedInventory<Beamable.Sui.Common.SuiCloudIdentity>
    {
        
        public SuiFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "SuiFederation";
            }
        }
        
        /// <summary>
        /// Call the InitializeContract method on the SuiFederation microservice
        /// <see cref="Beamable.Microservices.SuiFederation.SuiFederation.InitializeContract"/>
        /// </summary>
        public Beamable.Common.Promise<string> InitializeContract()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "InitializeContract", serializedFields);
        }
        
        /// <summary>
        /// Call the GetRealmAccount method on the SuiFederation microservice
        /// <see cref="Beamable.Microservices.SuiFederation.SuiFederation.GetRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("SuiFederation", "GetRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the GetContractAddress method on the SuiFederation microservice
        /// <see cref="Beamable.Microservices.SuiFederation.SuiFederation.GetContractAddress"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetContractAddress(string name)
        {
            object raw_name = name;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("name", raw_name);
            return this.Request<string>("SuiFederation", "GetContractAddress", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersSuiFederationClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForSuiFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<SuiFederationClient>();
        }
        
        public static SuiFederationClient SuiFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<SuiFederationClient>();
        }
    }
}
