//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.SuiFederation.SuiFederation"/> </summary
    public sealed class SuiFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedLogin<Beamable.Sui.Common.SuiCloudIdentity>, Beamable.Common.ISupportsFederatedInventory<Beamable.Sui.Common.SuiCloudIdentity>
    {
        
        public SuiFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "SuiFederation";
            }
        }
    }
    
    internal sealed class MicroserviceParametersSuiFederationClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForSuiFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<SuiFederationClient>();
        }
        
        public static SuiFederationClient SuiFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<SuiFederationClient>();
        }
    }
}
